name: Artron ðŸ“°
on:
  schedule:
    - cron: '*/5 9-2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        id: cache-npm
        uses: actions/cache@v3
        env:
           cache-name: cache-newz
        with:
           path: ~/.npm
           key: ${{ runner.os }}-newz-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-newz-${{ env.cache-name }}-
             ${{ runner.os }}-newz-
             ${{ runner.os }}-
      - name: ðŸ˜³ Build
        run: |
          rm -rf package.json
          npm install -g typescript
          npm install -g ts-node
          npm install jsdom @mozilla/readability sanitize-html @swc/wasm nano @types/node ulid
      - name: twentyfour
        run: |
          tsc ./.github/crons/_24.ts
          node ./.github/crons/_24.js
      - name: dnevnik
        run: |
          tsc ./.github/crons/_dnevnik.ts
          node ./.github/crons/_dnevnik.js
      - name: nova
        run: |
          tsc ./.github/crons/_nova.ts
          node ./.github/crons/_nova.js
      - name: mediapool
        run: |
          tsc ./.github/crons/_mediapool.ts
          node ./.github/crons/_mediapool.js
      - name: darik
        run: |
          tsc ./.github/crons/_darik.ts
          node ./.github/crons/_darik.js
      - name: sega
        run: |
          tsc ./.github/crons/_sega.ts
          node ./.github/crons/_sega.js
      - name: dir
        run: |
          tsc ./.github/crons/_dir.ts
          node ./.github/crons/_dir.js
